Repository josa-moa/josa-moa, pull requests merged in 2022-10, with the labels that each got.

#33 builder pattern 예제
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/Computer.java
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/TestBuilderPattern.java
Labels: enhancement, study

#31 220930_method_add
  src/main/java/kr/co/yermi/josamoa/service/JosamoaService.java
  src/main/java/kr/co/yermi/josamoa/service/JosamoaServiceImpl.java
  src/main/java/kr/co/yermi/josamoa/util/StringUtil.java
Labels: work

#34 josamoa BuilderPattern 적용
  README.md
  src/main/java/kr/co/yermi/josamoa/JosamoaTest.java
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/Josamoa.java
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/TestBuilderPattern.java
Labels: work

#35 create setJosa
  src/main/java/kr/co/yermi/josamoa/Josamoa.java
  src/main/java/kr/co/yermi/josamoa/JosamoaTest.java
  src/main/java/kr/co/yermi/josamoa/service/JosamoaService.java
  src/main/java/kr/co/yermi/josamoa/service/JosamoaServiceImpl.java
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/Computer.java
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/Josamoa.java
  src/main/java/kr/co/yermi/josamoa/test/builderPattern/TestBuilderPattern.java
  src/main/java/kr/co/yermi/josamoa/util/Constant.java
  src/main/java/kr/co/yermi/josamoa/util/JosamoaUtil.java
  src/main/java/kr/co/yermi/josamoa/util/StringUtil.java
  src/test/java/kr/co/yermi/josamoa/josamoaTests.java
Labels: enhancement, work

#36 Update README.md : josa-moa 1.0.2
  README.md
Labels: documentation
